name: CI
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: script
        run: |
          git clone https://salsa.debian.org/science-team/opencv.git
          cd opencv
          debuild
