name: CI
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04]
    steps:
      - uses: actions/checkout@v4
      - name: script
        run: |
          dget  http://ftp.riken.go.jp/Linux/ubuntu/pool/universe/o/opencv/opencv_4.10.0+dfsg-5ubuntu1.dsc
          sudo apt-get install -y build-essential devscripts debhelper cmake default-jdk dh-sequence-python3 doxygen dh-sequence-javahelper ninja-build libavcodec-dev libavformat-dev libdc1394-dev libeigen3-dev libgdal-dev libgdcm-dev libvtkgdcm-dev libgdcm-tools libgl-dev libglu1-mesa-dev libgoogle-glog-dev libgphoto2-dev libharfbuzz-dev libjpeg-dev liblapack-dev liblapacke-dev libleptonica-dev libopenexr-dev libopenjp2-7-dev libopenjpip-dec-server libopenjp2-tools libimath-dev libpng-dev libprotobuf-dev libqt5opengl5-dev libraw1394-dev libswscale-dev libtbb-dev libtesseract-dev libtiff-dev libv4l-dev libva-dev libvtk9-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev dh-sequence-maven-repo-helper ocl-icd-opencl-dev protobuf-compiler python3-all-dev dh-sequence-numpy3 python3-bs4 python3-imath qtbase5-dev
          git clone https://salsa.debian.org/science-team/opencv.git
          cd opencv
          echo "y" | debuild
